extra-deps:
- monad-memo-0.4.1
- multistate-0.7.1.1
- yaml-0.8.18.1 # For Windows. See <https://github.com/snoyberg/yaml/pull/91>.
- unsafe-0.0
packages:
- .
- extra-dep: true
  location:
    commit: b15f1ae585341ea312f712e63f29a0c57fa5f637
    git: https://github.com/lspitzner/butcher.git
- extra-dep: true
  location:
    commit: 605855659b15ff190d1e9c0c9b5e981e379aed15
    git: https://github.com/lspitzner/data-tree-print.git
- extra-dep: true
  location:
    commit: 85af8e4f34ff013575c9acd9675b495ee7f10180
    git: https://github.com/lspitzner/ghc-exactprint.git
resolver: nightly-2016-12-04
